### PR TITLE
adapt the code to latest changes in WebXR Viewer 1.07 and ARKit 1.5

### PR DESCRIPTION
**Pull request by vincentfretin**
Planes detection wasn't working anymore with latest WebXR Viewer 1.07 and ARKit 1.5.
I adapted your code to latest changes in the following commits
https://github.com/mozilla/webxr-polyfill/commit/e1c8596416fb4a704e62d7667dfa721d26ae1cef
https://github.com/mozilla/webxr-polyfill/commit/25a4390e51be2bc0944cbb3f74d92a93fc03b1dd#diff-c62474203acb6e8d87a081d92fb86569
https://github.com/mozilla/webxr-polyfill/commit/dc8ea763268db6409e834d30271d5f6bda63fc69#diff-c62474203acb6e8d87a081d92fb86569
and I added plane.vertices too.

I transformed 
```
mat4.fromRotationTranslation(hitVars.planeHit, hitVars.planeQuaternion, hitVars.planeIntersection);
```
from webvr-polyfill to the following THREE code:
```
hitVars.planeQuaternion.setFromRotationMatrix(hitVars.planeMatrix);
hitVars.planeHit.makeRotationFromQuaternion(hitVars.planeQuaternion).setPosition(hitVars.planeIntersection);
```
Is this correct?

### CODE REVIEW

**Comment by machenmusik** [comment]
Sorry about that!  I will take a look this weekend

**Comment by vincentfretin** [comment]
I learned a lot fixing it myself, so don't be sorry. ;-) Thanks for having created this in the first place, I can test on both my S8 on WebARonARCore and on my iPad with WebXR Viewer.

**Comment by vincentfretin** [comment]
btw in https://aframe-ar-plane.glitch.me/planes-example.js you have a comment "// anchor.vertices works for latest ARKit but not for latest ARCore; Float32Array issue?" . I can tell you that with latest WebARonARCore (which still uses arcore-preview.apk) I have anchor.vertices.

**Comment by vincentfretin** [comment]
With the https://aframe-ar-plane.glitch.me/ example on WebXR Viewer, I have poor planes detection (not big enough plane, or not merged planes) when using ar-raycaster (which actually try to intersect with every detected planes, not the same as with WebARonARCore which only does one sync hitTest).
So actually with 
```
<a-entity cursor="fuse:false"
                  raycaster="objects:.plane,.element;recursive:false" 
                  ar-raycaster="el:#ar-world"></a-entity>
```
it will try to intersect the planes twice, once with plane extent in hitTestNoAnchor, and another one with polygon geometry from aframe entity created in planes-example.js if I well understood the code.

I have sometimes issues when spawning an a-ring on raycast intersection, I don't see it, but I know it's there somewhere, can't really explain...
Just to be sure I enabled the raycaster only on plane extent via the ar-raycaster like this (removed .plane in objects):
```
<a-entity cursor="fuse:false"
                  raycaster="objects:.element;recursive:false" 
                  ar-raycaster="el:#ar-world"></a-entity>
```
I still have issues.

I know it's not the same part of the code that create the aframe entities for planes and the code doing the raycast, but it seems to me that it impacts the planes detection, maybe poor performance of the hitTestNoAnchor code that prevent handleFrame to execute sometime? Or an issue with the hitTestNoAnchor code? With or without the changes in hitTestNoAnchor in this PR, it's the same.

If I only do the raycast with the aframe entities like this
```
<a-entity cursor="fuse:false"
                  raycaster="objects:.plane,.element;recursive:false"></a-entity>
```
All is fine, the planes detection speed is great, like on the S8, I have no issue with spawning a a-ring on raycast intersection.

I think I will enable only ar-raycaster on WebARonARCore an not for WebXR Viewer for my use case for now.

**Comment by machenmusik** [comment]
My recollection is that WebXR Viewer implementation of AR hit test is inherently asynchronous, which actually I think comes from they way they do with iOS WebView, and so there may be some issues when compared to synchronous raycaster results... that was one of the original reasons for not processing all the AR hits, and appending rather than sorting.  The ARCore implementation is better IIRC, I don't recall about WebARonARKit but can try a sample if you have one.

**Comment by machenmusik** [comment]
The disadvantage of the direct integration with WebXR Viewer (acknowledged in discussions with Blair et al.), as opposed to using aframe-xr and their three.xr.js mods, is that it can be brittle when they change WebXR Viewer.  Last time I took a hard look was before 1.07, so many thanks for the proposed changes; I will try to give them a spin this weekend and merge if no issues.

**Comment by machenmusik** [comment]
What raycaster interval are you using when you see issues?  Every tick would be a problem...

**Comment by vincentfretin** [comment]
100ms `raycaster="objects:.plane,.element;recursive:false;interval:100"`
even if it's the default in aframe 0.7.1 I put it in the options to be sure to have this value when I'll switch to aframe 0.8.x because the default in this version is now 0.

**Comment by vincentfretin** [comment]
Do you know how to see console.log with WebXR Viewer? I enabled the develop menu in Safari on desktop and enabled Safari web introspector on iPad, I can see opened Safari page in the develop menu, but not WebXR Viewer opened page.

**Comment by machenmusik** [comment]
My recollection is that you have to make your own WebXR Viewer build with XCode, and set a configuration flag if the Mozilla code doesn't already, then that sort of thing works

**Comment by vincentfretin** [comment]
Just a follow up of the ar-raycaster issue I was having here, I think it was just the `hit[i]` issue, so my two points wasn't actually on the same plane, and I didn't see the segment between the two points because I was in the wrong orientation with an only front material. So all good now. :)

And so you know, the ar-raycaster on aframe 0.8.2 may not appear to work because it always intersect the same ar-world element. See my comment on https://github.com/aframevr/aframe/issues/3129#issuecomment-388568777

**Pull request merged**
